(setq x nil)
(print "enter list elements. enter -1 to stop entering list!")
(terpri)
(setq l (read-from-string (concatenate 'string "(" (read-line) ")")))
(print "enter n for nth element")
(terpri)
(setq n (read))
(format t "nth element is: ~d" (nth n l))
(terpri)